<a href="https://colab.research.google.com/github/madhumitha357/MLproject_BrainTumourDetection/blob/master/DataAugmentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install tensorflow


# New Section

In [ ]:
from keras.preprocessing.image import ImageDataGenerator

In [ ]:
pip install OpenCV-python

In [ ]:
import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator
import cv2
import imutils
import matplotlib.pyplot as plt
from os import listdir
#import time    
from PIL import Image
%matplotlib inline

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)



Mounted at /content/gdrive


In [ ]:
def hms_string(sec_elapsed):
    h = int(sec_elapsed / (60 * 60))
    m = int((sec_elapsed % (60 * 60)) / 60)
    s = sec_elapsed % 60
    return f"{h}:{m}:{round(s,1)}"

In [ ]:
def augment_data(file_dir, n_generated_samples, save_to_dir):
    
    
    
    
    data_gen = ImageDataGenerator(rotation_range=10, 
                                  width_shift_range=0.1, 
                                  height_shift_range=0.1, 
                                  shear_range=0.1, 
                                  brightness_range=(0.3, 1.0),
                                  horizontal_flip=True, 
                                  vertical_flip=True, 
                                  fill_mode='nearest'
                                 )
    c=0
    for filename in listdir(file_dir):
        print(filename)
        image = cv2.imread(file_dir + '/' + filename)
        print(image)
        image = image.reshape((1,)+image.shape)

        save_prefix = 'aug_' + filename[:-4]
        i=0
        
        c=c+1
        for batch in data_gen.flow(x=image, batch_size=1, save_to_dir=save_to_dir, 
                                           save_prefix=save_prefix, save_format='jpg'):
            i += 1
            print(c)
            c=c+1;
            if i > n_generated_samples:
                break

In [ ]:
augmented_data_path = '/content/gdrive/MyDrive/augumented'

augment_data('/content/gdrive/MyDrive/yes', 6,'/content/gdrive/MyDrive/augumented/yes')

augment_data('/content/gdrive/MyDrive/no', 9,'/content/gdrive/MyDrive/augumented/no')



Streaming output truncated to the last 5000 lines.
y781.jpg
[[[49 48 44]
  [49 48 44]
  [49 48 44]
  ...
  [48 47 43]
  [48 47 43]
  [48 47 43]]

 [[49 48 44]
  [49 48 44]
  [49 48 44]
  ...
  [48 47 43]
  [48 47 43]
  [48 47 43]]

 [[49 48 44]
  [49 48 44]
  [49 48 44]
  ...
  [48 47 43]
  [48 47 43]
  [48 47 43]]

 ...

 [[50 49 45]
  [50 49 45]
  [50 49 45]
  ...
  [50 49 45]
  [49 48 44]
  [49 48 44]]

 [[50 49 45]
  [50 49 45]
  [50 49 45]
  ...
  [50 49 45]
  [49 48 44]
  [49 48 44]]

 [[50 49 45]
  [50 49 45]
  [50 49 45]
  ...
  [50 49 45]
  [49 48 44]
  [49 48 44]]]
y739.jpg
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 

In [ ]:
augment_data('/content/gdrive/MyDrive/no', 9,'/content/gdrive/MyDrive/augumented/no')


1 no.jpeg
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
no 92.jpg
[[[165 167 168]
  [  0   0   1]
  [ 21  23  24]
  ...
  [ 20  22  23]
  [ 20  22  23]
  [ 20  22  23]]

 [[165 167 168]
  [  0   0   1]
  [ 21  23  24]
  ...
  [ 20  22  23]
  [ 20  22  23]
  [ 20  22  23]]

 [[165 167 168]
  [  0   0   1]
  [ 21  23  24]
  ...
  [ 20  22  23]
  [ 20  22  23]
  [ 20  22  23]]

 ...

 [[166 168 169]
  [  0   0   1]
  [ 22  24  25]
  ...
  [ 19  21  22]
  [ 19  21  22]
  [ 19  21  22]]

 [[166 168 169]
  [  0   0   1]
  [ 22  24  25]
  ...
  [ 20  22  23]
  [ 20  22  23]
  [ 20  22  23]]

 [[166 168 169]
  [  0   0   1]
  [ 22  

KeyboardInterrupt: ignored

In [ ]:
def data_summary(main_path):
    
    yes_path = main_path+'yes'
    no_path = main_path+'no'
        
    m_pos = len(listdir(yes_path))
    m_neg = len(listdir(no_path))
    m = (m_pos+m_neg)
    
    pos_prec = (m_pos* 100.0)/ m
    neg_prec = (m_neg* 100.0)/ m
    
    print(f"Number of examples: {m}")
    print(f"Percentage of positive examples: {pos_prec}%, number of pos examples: {m_pos}") 
    print(f"Percentage of negative examples: {neg_prec}%, number of neg examples: {m_neg}")


In [ ]:
data_summary('/content/gdrive/MyDrive/augumented/')

OSError: ignored

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
